import type { Metadata } from 'next'
import { Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import { ReactQueryProvider } from '@/components/react-query-provider'
import { ThemeProvider } from '@/components/theme-provider'
import { Appbar } from '@/components/Appbar'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { ClusterProvider } from '@/components/cluster-data-access'
import { Toaster } from '@/components/ui/sonner'
import { Analytics } from '@vercel/analytics/next'

export const metadata: Metadata = {
  title: 'Marketplacenft',
  description: 'Generated by create-solana-dapp',
}

const geist = Geist_Mono({
  subsets: ['latin'],
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${geist.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ReactQueryProvider>
            <ClusterProvider>
              <SolanaProvider>
                <Appbar />
                {children}
              </SolanaProvider>
            </ClusterProvider>
          </ReactQueryProvider>
          <Toaster richColors />
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  )
}
// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}
